version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: restobot-app:latest
    env_file:
      - .env
    ports:
      - "8089:8089"
    depends_on:
      - postgres
    environment:
      - MAIN_DB_URL=jdbc:postgresql://postgres:5432/main
      - MAIN_DB_USER=${MAIN_DB_USER}
      - MAIN_DB_PASSWORD=${MAIN_DB_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - TRIPADVISOR_API_KEY=${TRIPADVISOR_API_KEY}
      - TRIPADVISOR_API_HOST=${TRIPADVISOR_API_HOST}
      - TRIPADVISOR_API_LANGUAGE=${TRIPADVISOR_API_LANGUAGE}
    networks:
      - restobot-network

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${MAIN_DB_USER}
      - POSTGRES_PASSWORD=${MAIN_DB_PASSWORD}
      - POSTGRES_DB=main
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - restobot-network

volumes:
  postgres-data:

networks:
  restobot-network:
    driver: bridge 