apiVersion: v1
kind: Service
metadata:
  name: restobot-app
  labels:
    app: restobot-app
spec:
  type: NodePort
  selector:
    app: restobot-app
  ports:
    - name: http
      port: 8089
      targetPort: 8089
