/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.tishenko.restobot.integration;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
